MediBird/caring-note-api-server

src/main/java/com/springboot/api/common/converter/ListToStringConverter.java, src/main/java/com/springboot/api/common/exception/JsonConvertException.java, src/main/java/com/springboot/api/common/exception/handler/UserExceptionHandler.java, src/main/java/com/springboot/api/common/message/ExceptionMessages.java, src/main/java/com/springboot/api/controller/MedicationCounselController.java, src/main/java/com/springboot/api/domain/MedicationCounsel.java, src/main/java/com/springboot/api/dto/medicationcounsel/AddReq.java, src/main/java/com/springboot/api/dto/medicationcounsel/AddRes.java, src/main/java/com/springboot/api/dto/medicationcounsel/DeleteReq.java, src/main/java/com/springboot/api/dto/medicationcounsel/DeleteRes.java, src/main/java/com/springboot/api/dto/medicationcounsel/SelectByCounselSessionIdRes.java, src/main/java/com/springboot/api/dto/medicationcounsel/UpdateReq.java, src/main/java/com/springboot/api/dto/medicationcounsel/UpdateRes.java, src/main/java/com/springboot/api/repository/CounselCardRepository.java, src/main/java/com/springboot/api/repository/CounselSessionRepository.java, src/main/java/com/springboot/api/repository/CounseleeConsentRepository.java, src/main/java/com/springboot/api/repository/CounselorRepository.java, src/main/java/com/springboot/api/repository/MedicationCounselRepository.java, src/main/java/com/springboot/api/service/MedicationCounselService.java, src/test/java/com/springboot/api/controller/MedicationCounselControllerTest.java
feat: test APIs about MedicationCounsel
feat: Add APIs(update, delete MedicationCounsel)
feat: Add API(select MedicationCounsel By counselSessionId)
feat: Add API(add MedicationCounsel)
feat: add counselRecordHightlight in MedicationCounsel by @Convert
=> feat: add APIs about MedicationCounsel

src/main/java/com/springboot/api/common/config/security/SecurityConfig.java
feat: add contentSecurityPolicy for h2 admin
add contentSecurity for h2 admin, because of iframe
=> feat: add contentSecurityPolicy for h2 admin

src/main/java/com/springboot/api/controller/CounselCardController.java, src/main/java/com/springboot/api/controller/CounselSessionController.java, src/main/java/com/springboot/api/controller/CounseleeConsentController.java, src/main/java/com/springboot/api/controller/CounseleeController.java, src/main/java/com/springboot/api/controller/CounselorController.java, src/main/java/com/springboot/api/controller/MedicationCounselController.java, src/main/java/com/springboot/api/controller/SampleController.java, src/main/java/com/springboot/api/controller/UserController.java, src/main/java/com/springboot/api/dto/counselcard/SelectPreviousCounselCardItemListRes.java, src/main/java/com/springboot/api/service/CounselCardService.java, src/test/java/com/springboot/api/service/CounselCardServiceTest.java
feat: add API(selectPreviousListByCounselSessionId)
=> feat: add API for counsel card tab in counsel note

src/main/java/com/springboot/api/common/util/JwtUtil.java, src/main/java/com/springboot/api/domain/Counselee.java, src/main/java/com/springboot/api/domain/MedicationCounsel.java
fix
- delete @Lob
refator
- modify jwt expiration 10h to 48h for front test
=> Fix: jpa type convert error

src/main/java/com/springboot/api/controller/CounselCardController.java, src/main/java/com/springboot/api/controller/CounselSessionController.java, src/main/java/com/springboot/api/controller/CounseleeConsentController.java, src/main/java/com/springboot/api/controller/CounseleeController.java, src/main/java/com/springboot/api/controller/MedicationCounselController.java, src/main/java/com/springboot/api/domain/BaseEntity.java, src/main/java/com/springboot/api/service/CounselCardService.java, src/main/java/com/springboot/api/service/CounselSessionService.java, src/main/java/com/springboot/api/service/CounseleeConsentService.java, src/main/java/com/springboot/api/service/CounseleeService.java, src/main/java/com/springboot/api/service/MedicationCounselService.java, src/test/java/com/springboot/api/controller/CounselSessionControllerTest.java, src/test/java/com/springboot/api/service/CounselCardServiceTest.java, src/test/java/com/springboot/api/service/CounselSessionServiceTest.java, src/test/java/com/springboot/api/service/CounseleeServiceTest.java, src/test/java/com/springboot/api/service/MedicationCounselServiceTest.java
feat: add base entity column
In BaseEntity,
@PreCreate, @PreUpdate method
init createdBy, updatedBy column
So
remove useless parameter
=> Feature: add base entitiy column

src/main/java/com/springboot/api/controller/CounselSessionController.java, src/main/java/com/springboot/api/controller/CounseleeController.java, src/main/java/com/springboot/api/domain/CounselSession.java, src/main/java/com/springboot/api/dto/counselsession/SelectCounselSessionListItem.java, src/main/java/com/springboot/api/dto/counselsession/UpdateCounselorInCounselSessionReq.java, src/main/java/com/springboot/api/dto/counselsession/UpdateCounselorInCounselSessionRes.java, src/main/java/com/springboot/api/dto/counselsession/UpdateStatusInCounselSessionReq.java, src/main/java/com/springboot/api/dto/counselsession/UpdateStatusInCounselSessionRes.java, src/main/java/com/springboot/api/service/CounselSessionService.java, src/main/java/com/springboot/api/service/CounseleeService.java, src/main/java/com/springboot/enums/ScheduleStatus.java, src/test/java/com/springboot/api/service/CounselSessionServiceTest.java, src/test/java/com/springboot/api/service/CounseleeServiceTest.java
add updateStatusInCounselSession
refactor:  modify selectCounselSessionListByBaseDateAndCursorAndSize's dto
=> Refactor: counsel api home

src/main/java/com/springboot/api/common/config/security/JwtAuthenticationFilter.java, src/main/java/com/springboot/api/common/config/security/JwtAuthenticationProvider.java, src/main/java/com/springboot/api/common/config/security/SecurityConfig.java, src/main/java/com/springboot/api/common/config/security/SecurityProperties.java, src/main/java/com/springboot/api/repository/CounselSessionRepository.java, src/main/java/com/springboot/api/service/CounselSessionService.java, src/main/resources/application.yml, src/test/java/com/springboot/api/controller/CounselSessionControllerTest.java, src/test/java/com/springboot/api/repository/CounselSessionRepositoryTest.java, src/test/java/com/springboot/api/service/CounselSessionServiceTest.java
- jwt issue refact
- JPQL, LocalDateTime can't use IS NULL
=> Refactor: counsel session api

src/main/java/com/springboot/api/dto/counselee/SelectCounseleeBaseInformationByCounseleeIdRes.java, src/main/java/com/springboot/api/service/CounseleeService.java
add isDisability in response dto
=> refactor: counselee-api

build.gradle, src/main/java/com/springboot/api/controller/WasteMedicationController.java, src/main/java/com/springboot/api/domain/CounselSession.java, src/main/java/com/springboot/api/domain/WasteMedicationDisposal.java, src/main/java/com/springboot/api/dto/wasteMedicationDisposal/WasteMedicationDisposalReq.java, src/main/java/com/springboot/api/dto/wasteMedicationDisposal/WasteMedicationDisposalRes.java, src/main/java/com/springboot/api/repository/WasteMedicationDisposalRepository.java, src/main/java/com/springboot/api/service/WasteMedicationDisposalService.java, src/main/java/com/springboot/enums/wasteMedication/DisposalMethodType.java, src/main/java/com/springboot/enums/wasteMedication/DrugRemainActionType.java, src/main/java/com/springboot/enums/wasteMedication/RecoveryAgreementType.java, src/main/java/com/springboot/enums/wasteMedication/UnusedReasonType.java, src/main/resources/application.yml
H2에서 에러가 나는데..
리스트는 이렇게 캐스트 안하면 또 포스트그레에서 제대로 처리가 안되가지고.. 어떻게 해야할지 모르겠습니다.
=> feat: :sparkles: add wasteMedicationController

src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java, src/main/java/com/springboot/api/domain/WasteMedicationRecord.java, src/main/java/com/springboot/api/service/WasteMedicationRecordService.java
Builder 사용시 기본 생성자 지원 안됨 문제로 조회시 에러
=> revert: :fire: remove builder

src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java, src/main/java/com/springboot/api/service/CounseleeConsentService.java
fix **select counselConent 401 response issue**
=> Fix: counsel consent api

src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java, src/main/java/com/springboot/api/domain/CounselSession.java, src/main/java/com/springboot/api/domain/CounseleeConsent.java, src/main/java/com/springboot/api/dto/counseleeconsent/AddCounseleeConsentReq.java, src/main/java/com/springboot/api/service/CounseleeConsentService.java
=> fix: :recycle: remove relationship between counselSession and counseleeConsent

src/main/java/com/springboot/api/controller/CounseleeConsentController.java, src/main/java/com/springboot/api/dto/counseleeconsent/SelectCounseleeConsentByCounseleeIdRes.java, src/main/java/com/springboot/api/repository/CounseleeConsentRepository.java, src/main/java/com/springboot/api/service/CounseleeConsentService.java
Reverts MediBird/caring-note-api-server#87
=> Revert "fix: :recycle: refactor CounseleeConsentController"

src/main/java/com/springboot/api/domain/CounseleeConsent.java
Reverts MediBird/caring-note-api-server#89
=> Revert "fix: ♻️ fix CounseleeConsent"

src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java, src/main/java/com/springboot/api/domain/CounselSession.java, src/main/java/com/springboot/api/domain/CounseleeConsent.java, src/main/java/com/springboot/api/dto/counseleeconsent/AddCounseleeConsentReq.java, src/main/java/com/springboot/api/service/CounseleeConsentService.java
Reverts MediBird/caring-note-api-server#86
=> Revert "fix: :recycle: remove relationship between counselSession and counseleeConsent"

src/main/java/com/springboot/api/controller/CounseleeController.java, src/main/java/com/springboot/api/dto/counselee/SelectCounseleePageRes.java, src/main/java/com/springboot/api/service/CounselCardService.java, src/main/java/com/springboot/api/service/CounseleeService.java, src/test/java/com/springboot/api/controller/CounseleeControllerTest.java
Create SelectCounseleePagesRes
refactor SelectCounselees
=> feat: :recycle: refactor selectCounselees

.github/workflows/d-day-auto-labeler.yml
-
pr-auto-labeler 추가
없음
-
*
```
```
---
=> feat: :sparkles: add d-day-auto-labeler

src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java, src/main/java/com/springboot/api/counselsession/dto/counselsession/AddCounselSessionByCounseleeReq.java, src/main/java/com/springboot/api/counselsession/dto/counselsession/UpdateStartTimeInCounselSessionReq.java, src/main/java/com/springboot/api/counselsession/entity/CounselSession.java, src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java, src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java, src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java, src/test/java/com/springboot/api/controller/CounselSessionControllerTest.java, src/test/java/com/springboot/api/service/CounselSessionServiceTest.java, src/test/java/com/springboot/api/service/CounseleeServiceTest.java
- counselSession 예약 API, 상담일정 시간 수정 API 개발
- 상담일정 시작 일자 수정 API
- 상담세션(일정) 내담자 정보로 생성 API
- 없음
- TDD를 이용해서 개발해서, 테스트가 존재하나, 테스트가 모든 범위를 검사하고 있지는 않습니다.
- controller 부분에서 모든 에러를 검증하는 것에 대해서 어떻게 생각하는지 궁금합니다. 현재 controller test에서 모든 에러를 검사하지는 않습니다.
- validate 부분 테스트가 부족합니다. 
- service, controller 테스트 추가
- 깃 커밋이 조금 꼬여서, add, update를 재대로 분리해서 커밋하지 못했습니다.
```
- P3 : 이런 방법도 있을 것 같아요~ 등의 사소한 의견입니다 …
```
=> Feature/ add, update CounselSession API

src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java
-
- deprecated annotation 제거
없음
```
```
---
=> fix: :wastebasket: delete deprecated annotation

src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryImpl.java
- 내담자 이름 자동완성 기능 오류 해결
- query dsl 조건문 변경
- 없음
- 없음
* 없음
```
```
---
=> fix: :card_file_box: fix querydsl query

src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java, src/main/java/com/springboot/api/counselsession/entity/CounselSession.java, src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java, src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java, src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
[https://www.figma.com/design/BUJgUGjUoOg6IFEu6jX1Fx/%EC%BC%80%EC%96%B4%EB%A7%81-%EB%85%B8%ED%8A%B8?node-id=3198-199362&t=NRXwQ6JY3lnKcVlH-4](url)
상담 내역에서 전체 상담의 상담 회차를 셀렉트로 내놓아야 하므로 이에 따라 칼럼 추가
- counselSession entity 변경
- 없음
- session number 업데이트 부분 최적화 확인
* 없음
```
```
---
=> feat: :sparkles: add SessionNumber to CounselSession Entity

src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionPageRes.java, src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java
SelectCounselSession 응답 변경합니다.
-
-
-
*
```
```
---
=> refactor: :recycle: modify SelectCounselSessionRes

src/main/java/com/springboot/api/counselcard/entity/CounselCard.java, src/main/java/com/springboot/api/counselee/entity/Counselee.java, src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryImpl.java, src/main/java/com/springboot/api/counselor/entity/Counselor.java, src/main/java/com/springboot/api/counselsession/entity/AICounselSummary.java, src/main/java/com/springboot/api/counselsession/entity/CounselSession.java, src/main/java/com/springboot/api/counselsession/entity/CounseleeConsent.java, src/main/java/com/springboot/api/counselsession/entity/MedicationCounsel.java, src/main/java/com/springboot/api/counselsession/entity/MedicationCounselHighlight.java, src/main/java/com/springboot/api/counselsession/entity/MedicationRecord.java, src/main/java/com/springboot/api/counselsession/entity/MedicationRecordHist.java, src/main/java/com/springboot/api/counselsession/entity/PromptTemplate.java, src/main/java/com/springboot/api/counselsession/entity/WasteMedicationDisposal.java, src/main/java/com/springboot/api/counselsession/entity/WasteMedicationRecord.java
-  객체 연관 관계 최적화
- 사용하지 않는 @ OneToMany 삭제
- @ OnDelete 추가로 Cascade.DELETE 등록
@ OneToMany(cascade = CascadeType.ALL) 가 적용됩니다.
JPA 특성상 이를 적용하기 위해서는 테이블을 재성성 하거나 직접 쿼리로 설정해줘야합니다.
- @ OneToMany를 사용하는 객체에는 Fetch.LAZY 를 추가하여, N+1 문제를 막았습니다.
- 없음
- 양방향 관계를 제거한 상태로 CascadeType.ALL을 적용하는 방법으로는 2가지가 있습니다.
1. 직접 연관관계 걸린 객체 삭제
2. DB에 ON DELETE CASCADE 설정
이를 설정할 경우 DB엔진 자체에서 제거하기 때문에 Spring에서 삭제하지 않아도 삭제가 됩니다.
단 이 방식의 단점은 soft delete가 불가능해서, soft delete 도입시 제거해야합니다.
일단 현재 delete가 작동하지 않는 상태여서 2번을 사용했습니다.
차후에 soft delete를 도입하면서, 수정이 필요합니다.
```
- …
```
=> feat: add @OnDelete and Fetch.LAZY, remove useless @OneToMany

src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java, src/main/java/com/springboot/api/counselcard/service/CounselCardService.java, src/test/java/com/springboot/api/controller/CounselCardControllerTest.java
- CounselCardService 이동
- CounselCardService가 CounselSession 패키지에 있어서 이동했습니다.
- 없음
-
*
```
```
---
=> refactor: CounselCardService package and update imports

build.gradle, src/main/java/com/springboot/api/counselor/config/KeycloakAdminClient.java, src/main/java/com/springboot/api/counselor/controller/KeycloakUserController.java, src/main/java/com/springboot/api/counselor/service/KeycloakUserService.java, src/main/resources/application.yml
- 유저 삭제, 이름 변경 등 처리를 위한 준비
- 비밀번호 리셋 등
- keycloak admin client library 추가
- 없음
-
*
```
```
---
=> feat: :sparkles: add keycloak admin client library

src/main/java/com/springboot/api/counselee/dto/AddCounseleeReq.java
- Counselee 이름에 영어, 한글의외의 문자열 을 삽입할수 있음
- Counselee Name Validate 추가.
- 정규 표현식을 사용하여, 한글, 영어 빈칸으로 구성 되게 하고, 빈칸은 맨 앞이나 뒤에 오지 못하게 막음
- 없음
-
*
```
```
---
=> feat: update name validation regex

src/main/java/com/springboot/api/common/exception/ResourceNotFoundException.java, src/main/java/com/springboot/api/counselor/controller/CounselorController.java, src/main/java/com/springboot/api/counselor/dto/ResetPasswordReq.java, src/main/java/com/springboot/api/counselor/dto/UpdateRoleReq.java, src/main/java/com/springboot/api/counselor/service/CounselorService.java, src/main/java/com/springboot/api/counselor/service/KeycloakUserService.java, src/test/java/com/springboot/api/common/STTTest.java
- 카운셀러 삭제, 비밀번호 초기화 추가
- keycloak api 연동
- 없음 
-
*
```
```
---
=> feat: ✨ add apis for counselor

src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java
=> fix: fix SelectCounselSessionRes

src/test/java/com/springboot/api/service/CounselSessionServiceTest.java
=> test: add mock for CounselCardService in CounselSessionServiceTest

src/main/java/com/springboot/api/counselcard/dto/information/living/MedicationManagementDTO.java, src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
=> refactor: :recycle: refactor MedicationManagement

src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java, src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java, src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
=> feat: :sparkles: add ElementCollection

src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java, src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Exercise.java, src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Nutrition.java
=> refactor: :recycle: refactor not null constraints

src/main/java/com/springboot/api/counselcard/dto/information/base/CounselPurposeAndNoteDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/health/DiseaseInfoDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/independentlife/EvacuationDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/independentlife/WalkingDTO.java, src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java
=> refactor: :recycle: refactor set to list

src/main/java/com/springboot/api/counselcard/dto/information/health/DiseaseInfoDTO.java, src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java, src/main/java/com/springboot/api/counselee/dto/SelectCounseleeBaseInformationByCounseleeIdRes.java, src/main/java/com/springboot/api/counselee/service/CounseleeService.java
=> fix: :alien: update diseaseInfo to list

src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryImpl.java, src/main/java/com/springboot/api/counselor/repository/CounselorRepository.java, src/main/java/com/springboot/api/counselor/repository/CounselorRepositoryCustom.java, src/main/java/com/springboot/api/counselor/repository/CounselorRepositoryImpl.java, src/main/java/com/springboot/api/counselor/service/CounselorService.java
- 기록 보조자 맨 위로 올려달래요
- 커스텀 쿼리 생성
```
```
---
=> refactor: :recycle: refactor CounselorService query

src/main/java/com/springboot/api/common/converter/CustomJwtRoleConverter.java
- 이름 저장 로직 해결
- 한국어, 영어 이름 분리
- 없음
```
```
---
=> refactor: :recycle: refactor counselor name logic

src/main/java/com/springboot/api/counselee/service/CounseleeService.java
- 전화번호를 바꾸지 않고는, 내담자 정보를 변경 못하는 버그 수정
- 전화번호를 바꾸지 않고는, 내담자 정보를 변경 못하는 버그 수정
- 없음
-
*
```
```
---
=> fix: counselee change 

src/main/java/com/springboot/api/counselor/repository/CounselorRepository.java, src/main/java/com/springboot/api/counselor/service/CounselorService.java
- 약사 이상의 권한을 가진 사람들만 getCounselornames에 걸리도록 변경
- findAll -> findByRoleTypesIn
- 없음
```
```
---
=> fix: :passport_control: refactor get counselor names

src/main/java/com/springboot/api/counselsession/dto/aiCounselSummary/SpeakerStatsDTO.java
- 발화자 테스트 할때 잘 안잡힘.
- 발화자 선택 조건 변경 
- 발화자 수. 10 ->3
- 문자열 길이 5 -> 3
- 업음
-
```
```
---
=> refactor : filter condition change

src/main/java/com/springboot/api/counselor/entity/Counselor.java, src/main/java/com/springboot/api/counselor/repository/CounselorRepository.java, src/main/java/com/springboot/api/counselor/repository/CounselorRepositoryCustom.java, src/main/java/com/springboot/api/counselor/repository/CounselorRepositoryImpl.java, src/main/java/com/springboot/api/counselor/service/CounselorService.java, src/main/java/com/springboot/api/counselor/service/CounselorUserDetailsService.java, src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java, src/main/java/com/springboot/api/counselsession/entity/CounselSession.java, src/main/java/com/springboot/api/counselsession/entity/MedicationRecord.java, src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java, src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java, src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
- counselor에 soft delete 구현
- counselor에 있는 status를 이용하여 sort delete를 구현했습니다.
- findSessionByCursorAndDate counselor에서 나오는 N+1 쿼리 최적화
- counselSession이 캐시 삭제가 안되어서, 예전 데이터를 보여주는 버그를 수정
- counselSession에서 counslor update하는 쿼리 최적화
- Counselor에 Soft Delete  도입중에 생긴 문제가 있습니다. 
Counselor가 삭제를 한 다음에, DB에 걸려있는 email, phone_number, username으로 인해서 회원가입이 불가능합니다.
일단은 해당 이슈 남겨둔 상태로 PR올렸습니다.
* Keycloak에서 삭제를 진행하는 지에 대해서는 테스트를 진행하지 않았습니다.
* 기본적인 쿼리들은 테스트를 진행하였습니다.
```
- P2 : 반영을 …
```
=> Feature: soft delete on counselor

.gitignore, src/main/java/com/springboot/api/counselsession/dto/medicationRecordHist/AddAndUpdateMedicationRecordHistReq.java, src/main/java/com/springboot/api/counselsession/dto/medicationRecordHist/SelectMedicationRecordHistRes.java, src/main/java/com/springboot/api/counselsession/entity/MedicationRecordHist.java, src/main/java/com/springboot/api/counselsession/service/MedicationRecordHistService.java
- 일부 요소들이 null 이어도 의약물 상담이 저장되게 하려고 해요
- DTO 검증을 모두 완화시켰어요
- 없음
-
*
```
```
---
=> refactor: :recycle: refactor AddAndUpdateMedicationRecordHistReq

src/main/java/com/springboot/api/counselsession/service/MedicationRecordHistService.java
- resolve error of string to date parsing
- nullable 가능하게 변경
=> fix: :bug: fix string to null date error

src/main/java/com/springboot/api/counselsession/dto/medicationRecordHist/AddAndUpdateMedicationRecordHistReq.java
=> refactor: :safety_vest: remove validation from medicationId

src/main/java/com/springboot/api/counselsession/dto/medicationRecordHist/SelectMedicationRecordHistRes.java
=> fix: :bug: fix null medication bug

src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java, src/main/java/com/springboot/api/counselcard/dto/information/health/AllergyDTO.java, src/main/java/com/springboot/api/counselcard/dto/request/UpdateCounselCardReq.java, src/main/java/com/springboot/api/counselcard/entity/CounselCard.java, src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java, src/main/java/com/springboot/api/counselcard/entity/information/health/Allergy.java, src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java, src/main/java/com/springboot/api/counselcard/entity/information/health/MedicationSideEffect.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Exercise.java, src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Nutrition.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java, src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
- 동시성 이슈 회피를 위한 CounselCard 통합 수정 API
- CounselCard  전체 수정 API 개발
- AllergyDTO에서 boolean으로 사용되던 부분을 Boolean으로 변경 ( boolean은 기본값이 false이므로, null일때 false가 들어가게 된다.)
- API가 null check를 딱히 하지 않고, 없는 데이터 일 경우에는 업데이트 하지 않게 해두었습니다.
*
```
```
---
=> feat: add CounselCard Update API

src/main/java/com/springboot/api/common/exception/handler/GlobalExceptionHandler.java, src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java, src/main/java/com/springboot/api/counselcard/dto/information/base/CounselPurposeAndNoteDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/health/DiseaseInfoDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/independentlife/CommunicationDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/independentlife/EvacuationDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/independentlife/WalkingDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/living/DrinkingDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/living/ExerciseDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/living/MedicationManagementDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/living/NutritionDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/living/SmokingDTO.java, src/main/java/com/springboot/api/counselor/entity/Counselor.java, src/test/java/com/springboot/api/controller/CounselSessionControllerTest.java
- enum validation 제거
-
-
-
*
```
```
---
=> fix: :bug: delete valid enum annotations

src/main/resources/application.yml
-enum 타입 널처리
-
-
-
*
```
```
---
=> fix: :wrench: update jackson configuration

src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java, src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java, src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java, src/main/java/com/springboot/api/counselee/service/CounseleeService.java
- 내담자 삭제 버그 수정
- counselee에 걸린 내부 테이블들에 key 추가
- counselee 삭제 후 counselSession cache 삭제
-
*
```
```
---
=> Fix : delete counselee bug

src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java
=> fix: :bug: fix update communication bug

src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java
- [약사가 이전 상담 내역 조회 api 403 발생](https://www.notion.so/yoonyounglee/1c64b68481fb80d69592eb8811f39572?pvs=4)
- api role secured 변경
-
-
*
```
```
---
=> fix: :passport_control: modify api permission

src/main/java/com/springboot/api/common/annotation/ValidNullableEnum.java, src/main/java/com/springboot/api/common/validator/NullableEnumValidator.java, src/main/java/com/springboot/api/counselcard/entity/information/base/CounselPurposeAndNote.java, src/main/java/com/springboot/api/counselcard/entity/information/health/Allergy.java, src/main/java/com/springboot/api/counselcard/entity/information/health/DiseaseInfo.java, src/main/java/com/springboot/api/counselcard/entity/information/health/MedicationSideEffect.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Communication.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Evacuation.java, src/main/java/com/springboot/api/counselcard/entity/information/independentlife/Walking.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Exercise.java, src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Nutrition.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java, src/main/java/com/springboot/api/counselee/dto/UpdateCounseleeReq.java, src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
-  CounselCard 컬럼들 nullable하게 변경
- CounselCard 컬럼들 nullable하게 변경
- 반드시 True, False가 필요하거나, SmokingAmount 처럼 NONE으로 null을 표시하는 컬럼들은 not nullable 하게 유지
- ValidNullableEnum 어노테이션 추가
- Table Delete key 잘못 걸린 부분 수정
-
*
```
- P5: 그냥 사소한 의견입니다 …
```
=> Refactor: counsel card refactor

src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java, src/main/java/com/springboot/api/counselsession/entity/MedicationRecord.java, src/main/java/com/springboot/api/counselsession/entity/MedicationRecordHist.java, src/main/java/com/springboot/api/counselsession/entity/WasteMedicationRecord.java, src/main/java/com/springboot/api/medication/entity/Medication.java, src/main/java/com/springboot/api/medication/repository/MedicationRepository.java, src/test/java/com/springboot/api/service/MedicationServiceTest.java
- Medication 엔티티가 counselsession 패키지에 있습니다.
- Medication 엔티티를 medication으로 옮겼습니다.
- 없음
-
*
```
```
---
=> refactor: move Medication entity to medication package

build.gradle, src/main/java/com/springboot/api/counselee/dto/UpdateCounseleeReq.java, src/main/java/com/springboot/api/counselee/entity/Counselee.java, src/main/java/com/springboot/api/counselee/service/CounseleeService.java, src/test/java/com/springboot/api/controller/CounseleeControllerTest.java, src/test/java/com/springboot/api/fixture/CounseleeFixture.java, src/test/java/com/springboot/api/fixture/FixtureRandomUtil.java, src/test/java/com/springboot/api/service/CounseleeServiceTest.java
- https://www.notion.so/yoonyounglee/1b94b68481fb805da31fed1b17d6c4c7?pvs=4
- UpdateCounseleeReq에 최근 상담일 추가
- Counselee에서 전화번호 nullable하게 변경
- Counselee에서 key들을 모두 제거했습니다. 차후 비즈니스 로직을 보고 key들을 알맞게 추가해야 할 듯 합니다.
- CounseleeFixture 생성
- Counselee 업데이트 함수 리팩토링, 필드와 변경할 값이 둘다 null이면 오류 발생하는 부분 수정
- 없음
- Fixture 생성을 위해서,  
[네이버 Fixture Monkey](https://naver.github.io/fixture-monkey/v1-1-0/) 라이브러리를 사용했습니다.
Builder나 Setter가 없어도 값을 생성할 수 있고, 랜덤한 값을 넣어줍니다.
현재는 어느정도 도메인에 맞는 값들 중에서 랜덤으로 선택하게 하였지만, 완전 랜덤으로도 가능합니다.
지금은 테스트로 Counselee에만 도입했는데, 다음과 같은 테스트 데이터 생성 규칙을 제안합니다.
1. Request, Response DTO는 지금과 같이 builder나 생성자를 통해서 생성한다.
2. Entity에 관해서는 랜덤값 생성을 도입한다.
3. 완전 랜덤의 경우 알아볼 수 없는 문자열이 생성되니, 도메인에 맞는 문자열과 규칙을 도입한다.
✔개발자가 찾지 못하는 엣지 케이스를 찾기 위해서는 완전 랜덤을 도입해야 하는 지가 논의가 필요합니다.
문자열만 보시면 됩니다.
PS. 지금 대부분의 조회 로직이 …
=> Refactor: counselee 리팩토링 및 테스트 픽스처 추가

src/main/java/com/springboot/api/counselee/entity/Counselee.java
- 테이블 이름 지정
- 테이블 이름 지정
- 없음
-
*
```
```
---
=> refactor: add JPA table annotation to Counselee entity

src/main/java/com/springboot/api/counselcard/entity/CounselCard.java, src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
- 비장애인 노인분들도 자립생활역량 사용 가능하게 변경
- Counselee의 isDisability가 true 일 경우에만, CounselCard IndependentLife를 초기화 했는데, 해당 조건 삭제
- 사용하지 않는 join 쿼리 제거
-
*
```
```
---
=> feature: remove check disability info

src/main/java/com/springboot/api/counselcard/dto/information/living/DrinkingDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/living/ExerciseDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/living/MedicationManagementDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/living/NutritionDTO.java, src/main/java/com/springboot/api/counselcard/dto/information/living/SmokingDTO.java, src/main/java/com/springboot/api/counselcard/dto/response/CounselCardLivingInformationRes.java, src/main/java/com/springboot/api/counselcard/entity/CounselCard.java, src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
- 카운슬 카드 조회 오류 해결
- 카운슬카드 업데이트는 아직 문제 확인 못해봄
- 각 dto null 체크
- 없음
- update도 확인해봐야할듯
*
```
```
---
=> fix: :bug: prevent null pointer exception

src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
- couselsession service 코드가 tab size가 8로 되어있길래 4로 줄였습니다.
- couselsession service 코드가 tab size가 8로 되어있길래 4로 줄였습니다.
- 없음
-
*
```
```
---
=> refactor: resize tab size in couselsession service

src/main/java/com/springboot/api/counselcard/entity/CounselCard.java, src/main/java/com/springboot/api/counselsession/entity/CounselSession.java, src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepository.java, src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java, src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java, src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
- https://www.notion.so/yoonyounglee/1c04b68481fb804da2a0f4cd74e64d63?pvs=4
- 다회기 상담시, 자동 회차 상승 미반영
- CounselSession sessionNumber 재 정렬 함수 추가
Counselee의 CounselSession을 조회 후에, CounselSession Number가 맞지 않는 CounselSession을 업데이트
- CounselSessionRepository 미사용 함수 제거
- 이전 PR에서 CounselCard Id 부여를 옮기다가 지운듯 해서 복구
- 쿼리 최적화가 가능한 부분이 있는지 궁금합니다
*
```
- P5: 그냥 …
```
=> Feature: counsel session num

src/main/java/com/springboot/api/counselcard/entity/information/health/Allergy.java, src/main/java/com/springboot/api/counselcard/entity/information/health/MedicationSideEffect.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Drinking.java, src/main/java/com/springboot/api/counselcard/entity/information/living/Smoking.java
- CounselCard 엔티티 속성 nullable 하게 변경
- CounselCard 엔티티 속성 nullable 하게 변경
session id : 01JR6WQSX746MR5VSYQDWHGSZY 인 CounselCard를 보면 모두 null로 바꾸었습니다.
- DB는 수정해놓았습니다.
-
*
```
```
---
=> refactor: update counsel card column nullable

src/main/resources/application.yml
=> refactor: :wrench: refactor time problem

src/main/java/com/springboot/api/counselee/controller/CounseleeController.java, src/main/java/com/springboot/api/counselee/repository/CounseleeRepositoryImpl.java, src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
- counselor validation 삭제
- counselor validation 삭제
-
-
*
```
```
---
=> fix: :fire: remove counselor validation logic

src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java, src/main/java/com/springboot/api/counselsession/controller/AICounselSummaryController.java, src/main/resources/application.yml, src/test/java/com/springboot/api/controller/CounselCardControllerTest.java
- deprecated 된 함수 제거
- deprecated 된 함수 제거
- hibernate batch size 적용
- 없음
- deprecated 된 함수가 프론트에 적용이 되어있는지, stage에서 테스트 해볼 생각입니다.
- CounseleeCounsent 에 있는 Deprecated는 오늘 작업 내용이니 제외했습니다.
*
```
```
---
=> refactor: remove deprecated

README.md, build.gradle, docs/README.md
- 스웨거 버전 업데이트
- 그래들 빌드 변경
- 겸사 겸사 다른 패키지 업데이트
-
*
```
```
---
=> fix: :package: update package versions

src/main/java/com/springboot/api/counselcard/entity/information/living/MedicationManagement.java
- 실수로 Enumerated type을 삭제해버렸습니다.
- annotation 복원
- 없음
-
*
```
```
---
=> fix: :goal_net: fix enumerated error

src/main/resources/application.yml
- springboot actuator의 health 엔드포인트 허용
- springboot actuator의 health 엔드포인트 허용
- deployment에 readinessProbe를 추가하기 위해서 엔드포인트를 열었습니다.
- 없음
- 
*
```
```
---
=> feat: configure management endpoints for actuator health and discovery

src/main/java/com/springboot/api/common/config/security/SecurityConfig.java, src/main/java/com/springboot/api/tus/config/TusConstant.java, src/main/java/com/springboot/api/tus/config/TusProperties.java, src/main/java/com/springboot/api/tus/controller/TusController.java, src/main/java/com/springboot/api/tus/dto/response/TusFileInfoRes.java, src/main/java/com/springboot/api/tus/entity/TusFileInfo.java, src/main/java/com/springboot/api/tus/service/TusService.java, src/main/resources/application.yml
- TUS 프로토콜 오류 해결 및 파일 Merge 기능 추가
- TUS 프로토콜이 stage에서 prefix 문제가 생겨서 수정함
- 파일 Merge 기능 구현
- TusService 리팩토링
- 오타 수정
-
*
```
```
---
=> feature: add merge tus file

src/main/java/com/springboot/api/common/config/initializer/TestDataInitializer.java, src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java, src/main/java/com/springboot/api/counselsession/dto/counselsession/SearchCounselSessionReq.java, src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryCustom.java, src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java, src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
- 상담 세션 상태 필터 추가하고 싶어요
- 상담 세션 상태 필터 추가
- import 순서 변경
- 급하게 바꿨어욤.
*
```
```
---
=> feat: :sparkles: add counsel session status filters

src/main/java/com/springboot/api/tus/controller/TusController.java
```
❯❯❯ pnpm run generate:api
> caring-note-web@1.0.0 generate:api /Users/User/Documents/caring-note/caring-note-web
> openapi-generator-cli generate -i https://stg.caringnote.co.kr/api/v1/api-docs -g typescript-axios -o src/api --additional-properties=apiPackage=api,modelPackage=models,withSeparateModelsAndApi=true,apis,supportingFiles
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
| Error count: 1, Warning count: 0
Errors: 
-attribute paths.'/v1/tus/{fileId}'(patch).parameters.[Content-Type].content is missing
at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:717)
at …
```
=> fix: :bug: fix tus content type bug

src/main/java/com/springboot/api/counselee/dto/UpdateCounseleeReq.java, src/main/java/com/springboot/api/counselee/entity/Counselee.java, src/test/java/com/springboot/api/controller/CounseleeControllerTest.java, src/test/java/com/springboot/api/service/CounseleeServiceTest.java
- update counselee request  변경(사회보장타입 변경 가능하게)
- update counselee request  변경
- 없음
-
* 테스트 변경사항 있습니다.
```
```
---
=> refactor: :recycle: refactor UpdateCounseleeReq

src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java
- 탈퇴사용자 텍스트 노출 방식 오류 수정
- https://www.notion.so/yoonyounglee/1bf4b68481fb80b49a37cc5fc99d8a58?pvs=4
- 탈퇴사용자 조회 쿼리 변경
- 없음
-
*
```
```
---
=> refactor: update counselor information handling in CounselSessionRepository

src/main/java/com/springboot/api/counselor/entity/Counselor.java, src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectCounselSessionRes.java
- 상담 진행 필터 추가에 따른 UI 수정 & 취소상담 회차 표기 ‘-’처리
- https://www.notion.so/yoonyounglee/UI-1d54b68481fb8021988afb6b47bfa2d8?pvs=4
- SelectCounselSessionRes DTO 변경
-
-
*
```
```
---
=> refactor: update Counselor and SelectCounselSessionRes for improved structure and readability

src/main/java/com/springboot/api/common/util/FileUtil.java, src/main/java/com/springboot/api/tus/controller/TusController.java, src/main/java/com/springboot/api/tus/service/TusService.java
- 여러 파일 시도되서 머징 실패하면 전체 삭제하고 초기화
- 머징 실패시 삭제와 초기화 로직 생성
- 없음
-
*
```
```
---
=> refactor: :bug: delete files when error happend on merging

src/main/java/com/springboot/api/tus/controller/TusController.java, src/main/java/com/springboot/api/tus/dto/response/TusFileInfoRes.java, src/main/java/com/springboot/api/tus/service/TusService.java
- tus file info 받으려구요
-
-
-
*
```
```
---
=> refactor: :recycle: refactor fileid to counselsession id

src/main/java/com/springboot/api/tus/service/TusService.java
=> fix: :bug: declare entitymanger.flush

src/main/java/com/springboot/api/counselsession/controller/CounselSessionController.java, src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectPreviousCounselSessionDetailRes.java, src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java
- 다회차 지원을 위한 이전 상담 히스토리 api 생성
- api 추가
- dto 추가
- service 추가
- 없음
- 특이사항 없음
* 없음
```
```
---
=> feat: :sparkles: 이전 상담 내역 상세 조회 API 추가 및 서비스 로직 구현

src/main/java/com/springboot/api/counselcard/controller/CounselCardController.java, src/main/java/com/springboot/api/counselcard/dto/response/MainCounselBaseInformationRes.java, src/main/java/com/springboot/api/counselcard/dto/response/MainCounselHealthInformationRes.java, src/main/java/com/springboot/api/counselcard/dto/response/MainCounselIndependentLifeInformationRes.java, src/main/java/com/springboot/api/counselcard/dto/response/MainCounselLivingInformationRes.java, src/main/java/com/springboot/api/counselcard/dto/response/MainCounselRecord.java, src/main/java/com/springboot/api/counselcard/dto/response/MainCounselRecordBuilder.java, src/main/java/com/springboot/api/counselcard/repository/CounselCardRepositoryCustom.java, src/main/java/com/springboot/api/counselcard/repository/CounselCardRepositoryImpl.java, src/main/java/com/springboot/api/counselcard/service/CounselCardService.java
- 본상담에서 기초 설문 내역 리뉴얼
- 본 상담용 상담 카드 조회 API 4종이 추가되었습니다.
- 상담 카드 데이터는 지금 상담 세션의 데이터와 과거 상담 세션의 데이터를 제공합니다.
과거데이터는 날짜와 함께 주어집니다.
- 기존 본상담에서 사용하던 API deprecated 처리
- 데이터 형식을 일단 피그마 보고 맞춰보았는데, 수정 사항이 필요하면 말씀해주세요
*
```
```
---
=> feat: renew consult counsel card

src/main/java/com/springboot/api/common/exception/NoContentException.java, src/main/java/com/springboot/api/common/util/AiResponseParseUtil.java, src/main/java/com/springboot/api/counselsession/controller/AICounselSummaryController.java, src/main/java/com/springboot/api/counselsession/dto/counselsession/SelectPreviousCounselSessionDetailRes.java, src/main/java/com/springboot/api/counselsession/service/AICounselSummaryService.java, src/main/java/com/springboot/api/counselsession/service/CounselSessionService.java, src/test/java/com/springboot/api/common/util/AiResponseParseUtilTest.java
- NoContentException 클래스에 스택트레이스를 생성하지 않도록 수정하여 성능 최적화
- AI 응답 파싱을 위한 AiResponseParseUtil 클래스 추가, JSON 구조에서 안전하게 데이터 추출 기능 구현
- AICounselSummaryService에서 AI 응답 파싱 유틸리티 사용하여 코드 간소화
-
- NoContentException 클래스에 스택트레이스를 생성하지 않도록 수정하여 성능 최적화
- AI 응답 파싱을 위한 AiResponseParseUtil 클래스 추가, JSON 구조에서 안전하게 데이터 추출 기능 구현
- AICounselSummaryService에서 AI 응답 파싱 유틸리티 사용하여 코드 간소화
-
-
*
```
- Comment 작성 …
```
=> feat: NoContentException 클래스 개선 및 AI 응답 파싱 유틸리티 클래스 추가

src/main/java/com/springboot/api/counselor/controller/CounselorController.java, src/main/java/com/springboot/api/counselor/dto/ChangePasswordReq.java, src/main/java/com/springboot/api/counselor/dto/UpdateMyInfoReq.java, src/main/java/com/springboot/api/counselor/service/CounselorService.java
- 내 정보 업데이트 API 및 DTO 추가
- 비밀번호 변경 API 및 DTO 추가
- 계정 탈퇴 API 구현
- 관련 서비스 로직 추가 및 예외 처리 개선
- 내 정보 팝업에 필요한 API 구현
- 탈퇴, 비번 변경, 정보 업데이트 (이름, 전화번호 변경
- API 세 개 추가
- 없음
-
*
```
```
---
=> feat: 내 정보 업데이트 및 비밀번호 변경 기능 추가

src/main/java/com/springboot/api/counselor/service/CounselorService.java
- [이전 pr](https://github.com/MediBird/caring-note-api-server/pull/261) 에서 제기된 문제 해결
- 상담사 정보 업데이트 시 이름과 전화번호를 직접 설정하도록 변경
- Keycloak 사용자 삭제 로직에서 사용자명 확인 절차 간소화
- 불필요한 예외 처리 코드 제거
-
-
*
``` …
```
=> refactor: 상담사 정보 업데이트 로직 간소화 및 Keycloak 사용자 삭제 로직 개선

src/main/java/com/springboot/api/counselsession/repository/CounselSessionRepositoryImpl.java
- 오래된 진행 상태 상담 세션 취소 처리
- 쿼리에 진행상태 추가
- 없음
-
*
```
```
---
=> refactor: 크론잡에서 진행 상태 상담 세션도 취소 처리하도록 변경

src/main/java/com/springboot/api/counselor/dto/ChangePasswordReq.java
=> refactor: ChangePasswordReq 클래스에서 현재 비밀번호 필드 제거
